FROM node:22-alpine AS base

WORKDIR /app

COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY packages ./packages
COPY apps ./apps

RUN corepack enable

ARG SERVICE_PATH

RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter ${SERVICE_PATH} build

CMD ["sh", "-c", "echo Set a service-specific command in docker-compose && sleep infinity"]
